### ISSUE TITLE
wrapper.h:1:10: fatal error: 'assimp/cimport.h' file not found

### ISSUE THREAD

**Issue by AntonioNoack** [jkvargas/russimp-sys#21]
Hello, when I add russimp as a dependency to my Rust project,
I get the following error:

```
   Compiling russimp-sys v0.2.4
error: failed to run custom build command for `russimp-sys v0.2.4`

Caused by:
  process didn't exit successfully: `C:\Users\Antonio\Documents\IdeaProjects\RustEngine\patina_engine\target\debug\build\russimp-sys-8391213aad959fd2\build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=user32
  cargo:rustc-link-lib=gdi32

  --- stderr
  wrapper.h:1:10: fatal error: 'assimp/cimport.h' file not found
  wrapper.h:1:10: fatal error: 'assimp/cimport.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', C:\Users\Antonio\.cargo\registry\src\github.com-1ecc6299db9ec823\russimp-sys-0.2.4\build.rs:31:10
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
     1: core::panicking::panic_fmt
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
     2: core::result::unwrap_failed
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\result.rs:1355
     3: enum$<core::result::Result<bindgen::Bindings, tuple<>>, 0, 1, Ok>::unwrap<bindgen::Bindings,tuple<>>
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\result.rs:1037
     4: build_script_build::main
               at .\build.rs:29
     5: core::ops::function::FnOnce::call_once<fn(),tuple<>>
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I am using Windows 10, Cargo version 1.54.0, LLVM Version 12.0.1 (just installed it for this purpose)

C:\Users\Antonio\Documents\IdeaProjects\RustEngine\patina_engine is the location of my Rust project.

**Comment by CravenWarrior3** [comment]
It's the same issue I had in #19, although I don't know how to install the dependency on Windows.

**Comment by jkvargas** [comment]
hi Antonio and Craven,
I am not a windows user myself.
But I will try to help you the best way I can.
First, for purposing of using the library you will not need LLVM :)
unless you want to build assimp yourself, which I don't think you want to.
I will update the documentation in a proper way.

Now, for windows usage,
we had a contributor in the past who wrote the pipeline that is building for windows, https://github.com/jkvargas/russimp-sys/blob/main/.github/workflows/russimp-sys.yml
I remember he saying to me that in order to use it on windows you will need vcpkg.
https://vcpkg.io/en/index.html
then you will need to install assimp from vcpkg.
If you find out how to do it, please share with me so I can update the docs for other users, or if you want to update the README yourself then feel free to open a pull request.
One contributor gave some extra information on using russimp on windows,
https://github.com/jkvargas/russimp/pull/16
